name: catiptv

on:
  schedule:
    # 每天北京时间上午 8 点运行 (UTC 0:00)
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动点击运行

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest # 修正这里：由 runs-with 改为 runs-on
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python catiptv.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [ -f live.m3u ]; then
            git add live.m3u
            git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
            git push
          fi
