name: catiptv

on:
  schedule:
    //- cron: '0 */6 * * *' # 每 6 小时自动检查一次
  workflow_dispatch:      # 允许手动触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # 取消浅克隆，确保 rebase 正常运行
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests urllib3

      - name: Run script
        run: python catiptv.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 检查 live.m3u 是否有实质性修改
          if [ -n "$(git status --porcelain live.m3u)" ]; then
            git add live.m3u
            git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M:%S')"
            
            # 推送前拉取并变基，解决 [rejected] main -> main 错误
            git pull --rebase origin main
            git push origin main
          else
            echo "源文件未检测到变化，跳过推送。"
          fi
